### PR TITLE
Adding PCNT notation support

### PR DESCRIPTION
**Pull request by davidrabinowitz**

### CODE REVIEW

File: bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryUtilTest.java [hunk 1]
```diff
@@ -182,6 +182,14 @@ public void testUnparsableTable() {
     assertThrows(IllegalArgumentException.class, () -> BigQueryUtil.parseTableId("foo:bar:baz"));
   }
 
+  @Test
+  public void testProjectCatalogNamespaceTableNotation_independent() {
+    TableId tableId =
+        BigQueryUtil.parseTableId(
+            "table", Optional.of("catalog.namespace"), Optional.of("project"));
+    assertThat(tableId).isEqualTo(TableId.of("project", "catalog.namespace", "table"));
+  }
```
[the remark this answers is not in the document]
Comment (davidrabinowitz) [reply bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryUtilTest.java:240]: @gemini-code-assist check `testProjectCatalogNamespaceTableNotation_four_part()`

File: bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java [hunk 2]
```diff
@@ -225,6 +226,22 @@ public static TableId parseTableId(
     String table = matcher.group(5);
     Optional<String> parsedDataset = Optional.ofNullable(matcher.group(4));
     Optional<String> parsedProject = Optional.ofNullable(matcher.group(3));
+
+    if (parsedProject.isPresent() && parsedDataset.isPresent()) {
+      String projectStr = parsedProject.get();
+      if (projectStr.contains(".") && !projectStr.contains(":")) {
```
Comment (yalimu-g) [inline bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java]: Should we create constant for this given it used multiple times here?

**Review by yalimu-g — DISMISSED** [review]

File: spark-bigquery-dsv2/spark-4.1-bigquery-lib/pom.xml [hunk 3]
```diff
@@ -14,8 +14,9 @@
   <name>Connector code for BigQuery DataSource v2 for Spark 4.1</name>
   <properties>
     <maven.compiler.release>17</maven.compiler.release>
-    <spark.version>4.1.0</spark.version>
     <scala.binary.version>2.13</scala.binary.version>
+    <spark.minor.version>4.1</spark.minor.version>
+    <spark.version>4.1.0</spark.version>
```
Comment (vinayakumarb) [inline spark-bigquery-dsv2/spark-4.1-bigquery-lib/pom.xml:20]: Can we upgrade to 4.1.1?

**Review by vinayakumarb — CHANGES_REQUESTED** [review]

File: spark-bigquery-dsv2/spark-4.1-bigquery-lib/pom.xml (hunk 3 above)
Comment (davidrabinowitz) [reply spark-bigquery-dsv2/spark-4.1-bigquery-lib/pom.xml:20]: The connector always complied against the base version (X.Y.0), to verify that some hidden behaviour won't allow users to use it on previous versions (e.g. we compile with 3.5.7 and now 3.5.3 users run into issues)

**Review by BoqianShi — APPROVED** [review]
Integration tests are fixed right now after migrating to us-central1, specifically I:

 Merged latest `master` into the branch to resolve the `pom.xml`/`CHANGES.md` conflicts and pick up the recent dependency train. The core change here is bumping **google-cloud-bigquery to 2.69.0**, which adds `@Nullable` to `BigLakeConfiguration` and fixes the NPE when reading Iceberg REST Catalog / unified-table tables that legitimately have no `connectionId`. Because 2.69.0 transitively pulls **google-cloud-core 2.73.0** — which references `gax-httpjson`'s `HttpJsonConscryptUtils` (absent in gax 2.82.0) and would otherwise force gax 2.83.0 + conscrypt 2.6.0 — I've pinned **google-cloud-core to 2.72.0**. This keeps the dependency set coherent with gax 2.82.0 / conscrypt 2.5.2 (identical to `master`'s runtime classpath except the bigquery jar) and resolves the `CustomCredentialsIntegrationTest` `NoClassDefFoundError`. 

Verified locally (lakehouse IRC read + credentials tests pass) and via gcb.
