### ISSUE TITLE
ClassNotFoundException: autovalue.shaded.com.google$.common.base.$Strings raised from bigquery with auto-value 1.10

### ISSUE THREAD

**Issue by emilyreff7** [GoogleCloudDataproc/spark-bigquery-connector#838]
After upgrading auto-value from 1.8.2 to 1.10, we have hit the following error that seems to be caused by incorrect shading of autovalue in bigquery:
```
Caused by: java.lang.NoClassDefFoundError: autovalue/shaded/com/google$/common/base/$Strings
	at com.google.cloud.spark.bigquery.repackaged.com.google.auto.value.processor.Nullables.<init>(Nullables.java:60)
	at com.google.cloud.spark.bigquery.repackaged.com.google.auto.value.processor.AutoAnnotationProcessor.init(AutoAnnotationProcessor.java:104)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:701)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:828)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:924)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:916)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	... 12 more
Caused by: java.lang.ClassNotFoundException: autovalue.shaded.com.google$.common.base.$Strings
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 23 more
```

It seems the shading defined for autovalue in bigquery is incorrect (or somehow breaks with 1.10), and it should actually be looking for `...repackaged.autovalue.shaded...` instead of `autovalue.shaded.com.google...`.

**Comment by davidrabinowitz** [comment]
Strange, as the `autovalue/shaded/...` classes are not repackaged, and `autovalue.shaded.com.google$.common.base.$Strings` is there:
```
$ unzip -l spark-bigquery-with-dependencies_2.12-0.27.1.jar | grep autovalue | grep Strings
     6521  2021-12-14 16:25   autovalue/shaded/com/google$/common/base/$Strings.class
```

It may be Java 11 issue

**Comment by emilyreff7** [comment]
Yes this error hits on Java 11.
